### ISSUE TITLE
DMN Editor's Boxed Expression Editor: FEEL function documentation is not rendered

### ISSUE THREAD

**Issue by jomarko** [apache/incubator-kie-issues#431] opened 2023-08-16 04:22 UTC
We have a regression of #353 feature. Once user tries to display FEEL function documentation. It is not rendered and an error appears in the browser console log.

![image](https://github.com/kiegroup/kie-issues/assets/8044780/48f024ea-68a7-4cf0-97e6-b2156a508b2d)

**Comment by tiagobento** [comment] 2023-08-16 20:46
@jomarko Any idea what commit introduced this regression? Might be good to know so we can assess the effort it would take to fix it.

**Comment by jomarko** [comment] 2023-08-21 09:01
@tiagobento I do not know the commit. My investigation brings this:
- the issue **is** reproducible on https://sandbox.kie.org/
- the issue **is** reproducible on https://sandbox.kie.org/dev
- the issue **is not** reproducible on main built as: `pnpm -F online-editor... build:dev`

It brings me to a suspicion, it is somehow related to `build:prod` . Do you think it is possible we pack some js libraries that are in conflict, or something similar?

**Comment by yesamer** [comment] 2023-08-21 09:08
@jomarko I just investigated, and I concur with your conclusions. In addition

- the issue **is not** reproducible on VSCode Extension

**Comment by yesamer** [comment] 2023-08-22 14:09
@tiagobento The root cause of the issue could be related to this BUG reported in monaco-editor: https://github.com/microsoft/monaco-editor/issues/3035
In my understanding, that issue affects the version we're currently using (0.33.0)
Not clear if the bug was fixed, but it could make sense to update monaco-editor to the latest version (0.39.0).
I noticed that @danielzhe already updated the version in his 168 ticket, we can use his branch to check if fixed.

**Comment by tiagobento** [comment] 2023-08-22 16:59
It might be something regarding the configuration of Monaco on build:prod, like @jomarko mentioned...  I'm working on #439 and the documentation for functions listed on autocomplete is working normally on the Dev webapp I put together...

**Comment by yesamer** [comment] 2023-08-25 10:13
It seems it doesn't reproduce anymore in https://github.com/kiegroup/kie-tools/pull/1869, PR where monaco-editor has been updated to the latest version ( tested here https://danielzhe.github.io/feel/dist/#/). 
I'll re-test after the PR merge. If confirmed, I'll close this accordingly.

**Comment by jomarko** [comment] 2023-08-25 10:23
@yesamer yes, I agree with that proposal. Feel free to close it if not reproducible.

**Comment by yesamer** [comment] 2023-09-27 07:41
Fixed by https://github.com/kiegroup/kie-tools/pull/1869

**Closed as completed** 2023-09-27 07:41 UTC
Labels: type:bug, area:dmn, area:tools
