### ISSUE TITLE
Support `context` Data Type on inputs/outputs of DMN Runner

### ISSUE THREAD

**Issue by tiagobento** [apache/incubator-kie-issues#225] opened 2023-04-20 15:44 UTC
Now, the `context` Data Type is not supported by the DMN Runner table. Adding an input with the `context` Data Type will render a text input field, which will essentially be a `string`.  This causes to send a `string` to the JIT Executor, and the `context` value is not correctly evaluated.

### Steps do Reproduce
 - Create a new DMN file;
 - Add a Input node called `myInput` and a Decision node called `myDecision`;
 - Change the Input node type to `context`;
 - Add the following Literal Expression in the Decision node: `myInput.x`;
 - Open the DMN Runner, and fill the `myInput` field with: `{ "x": 1 }`;
 - The output value should be `1` but it's `null`;

### Example

https://user-images.githubusercontent.com/24302289/234119678-f6aa7921-2660-4dbe-8305-60abb5ae1a57.mp4

```[tasklist]
### Acceptance criteria
- [ ] The DMN Runner table should correctly evaluate the "context" type.
```

**Comment by jomarko** [comment] 2023-04-24 12:49
I think this is a duplicate of https://github.com/kiegroup/kie-issues/issues/19 ? Should we close one of the issues?

**Comment by ljmotta** [comment] 2023-05-03 21:13
@jomarko No, on #19 we need to implement a new component for the `context` type, which will validate (or not) the FEEL expressions, probably using the monaco editor, it requries more investigation. This current issue is to be able to correctly evaluate `context` expressions on the DMN Runner table. Now, the DMN Runner form correctly sends a `object` to the JIT executor, and the DMN Runner table sends a `string`.

**Closed as completed** 2023-05-09 20:02 UTC
Labels: type:bug, area:dmn
