### ISSUE TITLE
The DMN runner (as Table) does not display property names, and the scrollbar is missing.

### ISSUE THREAD

**Issue by phungvannarich-kepler-aavn** [apache/incubator-kie-issues#1649] opened 2024-11-29 04:57 UTC
Here is some issue when I am working with DMN runner (as table).
I am using the KIE Sandbox [here ](https://sandbox.kie.org/dev/) to reproduce the issue.

1. Missing Property Name
We **can see** the property names in the table when the data type is **not** a collection:
![image](https://github.com/user-attachments/assets/c5302e64-5510-4594-8b3e-a4aaf2a2ab2d)

We **cannot see** the property names in the table when the data type **is a collection**:
![image](https://github.com/user-attachments/assets/1d282adc-9dc9-4897-b06d-aec86a6a464f)

2. There is no scrollbar when there are many columns, so we cannot scroll to the right to edit the table.

I wonder if these are current issues or if they occur because I am using it incorrectly?

**Comment by jomarko** [comment] 2024-11-29 05:39
Hi @phungvannarich-kepler-aavn , I believe this issue is a duplicate of https://github.com/apache/incubator-kie-issues/issues/378. So you spot a real issue.

**Comment by yesamer** [comment] 2024-11-29 06:54
@phungvannarich-kepler-aavn Please update https://github.com/apache/incubator-kie-issues/issues/378 with your findings and close this as duplicate, thanks.

**Closed as not planned** 2024-11-29 07:23 UTC
Labels: type:bug, area:dmn, area:tools
