### ISSUE TITLE
Workspace content drawer keeps open after deleting the workspace on KIE Sandbox Home page

### ISSUE THREAD

**Issue by pefernan** [apache/incubator-kie-issues#128] opened 2023-03-02 15:27 UTC
In the *Recent Models* section, if you try to delete a Workspace with the content's drawer expanded, the workspace is successfully deleted but the contents drawer keeps opened.

![Image](https://user-images.githubusercontent.com/2429832/222470705-79b7d4fa-7919-4538-8cb2-034684a2f126.gif)

**Comment by tiagobento** [comment] 2023-03-02 15:40
@pefernan I don't think that's wrong to upload a new file like this.. I'd say that KIE Sandbox is behaving well in this case. 

When deleting the last workspace, indeed you're working, we should be closing the drawer. Can you please change this issue to be only about this deletion bug?

**Comment by pefernan** [comment] 2023-03-02 16:02
@tiagobento ok, but I still think that a notification would be good for the user.

**Comment by tiagobento** [comment] 2023-03-02 16:10
@pefernan But there's no error... User requested to upload a file, and a file was uploaded, I don't understand what is wrong with this workflow.

**Comment by pefernan** [comment] 2023-03-02 16:22
@tiagobento nothing wrong with the workflow, actually I wasn't expecting that behaviour and maybe a notification would have been helpful.

**Comment by tiagobento** [comment] 2023-03-03 11:06
@pefernan What would this notification say?

**Comment by Josephblt** [comment] 2023-08-02 13:22
Hello @pefernan, @tiagobento. I could not reproduce this error during the 0.31.0-prerelease Sanity Checks. We can close this issue. WDYT?

**Comment by thiagoelg** [comment] 2023-08-02 19:28
Looks like there was a duplicate issue about this here: https://github.com/IBM/kie-roadmap/issues/187

It was fixed here: https://github.com/kiegroup/kie-tools/pull/1863

I'm closing it, thanks for testing @Josephblt!

**Closed as completed by thiagoelg** 2023-08-02 19:28 UTC
Labels: type:bug, area:tools
