### ISSUE TITLE
Exception/Error thrown in a sub-process doesn't reach the boundary error in the parent Service Task

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#107] opened 2023-02-10 08:02 UTC
When an error is thrown in a sub-process' terminal error node, it is not propagated to the boundary error node in the parent's service task. The terminal error node and the boundary error node are defined with the exact same error code.

Filed in the Red Hat JIRA: [KOGITO-8652](https://issues.redhat.com/browse/KOGITO-8652)

**Comment by tiagobento** [comment] 2023-02-13 11:32
@elguardian I'm assuming you're the one working on this, so assigning it to you.

**Comment by tiagobento** [comment] 2023-04-28 21:07
@elguardian Do we have a PR to link here? This is "Done" in the board but the issue is still open...

**Comment by elguardian** [comment] 2023-05-24 14:41
there is no left anything to do here. this should be done.

**Closed as completed by elguardian** 2023-05-24 14:41 UTC
Labels: type:bug, misc:good-first-issue, area:bpmn
