### ISSUE TITLE
KIE editor can't import dmn or associate dmn with scesim when in a multi-root VSCode workspace

### ISSUE THREAD

**Issue by gbuckholtz** [apache/incubator-kie-issues#1623] opened 2024-11-18 16:03 UTC
It took some time to boil this one down but that is what is happening.  I have a multi-root workspace and when I open a dmn file with an included model, it says that there are 0 rules in it. Additionally, I can't re-add the included model,  the dropdown can't find it.  The same sort of thing goes with the scesim, it can't find the associated dmn when opened in in a workspace and I can't re-choose the dmn because it doesn't show up in the dropdown list.  

All these problems go away when I open the project explicitly and not part of a workspace.  The only thing that changes in my test is viewing project directly and opening the workspace.  No files were altered.

**Comment by yesamer** [comment] 2024-11-19 07:31
Duplicate of https://github.com/apache/incubator-kie-issues/issues/602
@gbuckholtz please put your comment in the above issue ^^

**Closed as not planned by yesamer** 2024-11-19 07:31 UTC
